<?php

declare(strict_types=1);

$imgBase = 'https://www.hungrylion.co.za/wp-content/uploads';

return [
    'hero-slides' => [
        ['desktop' => $imgBase . "/2026/06/RSA_Football-Meal_FFF_Desktop.jpg", 'mobile' => $imgBase . "/2026/06/RSA_Football-Meal_FFF_Mobile.jpg", 'alt' => 'Football Meal'],
        ['desktop' => $imgBase . "/2026/06/RSA_Football-Meal_FDH_Desktop.jpg", 'mobile' => $imgBase . "/2026/06/RSA_Football-Meal_FDH_Mobile.jpg", 'alt' => 'Football Meal'],
        ['desktop' => $imgBase . "/2026/06/RSA_Matchday_FF_Desktop-1_50.webp", 'mobile' => $imgBase . "/2026/06/RSA_Matchday_FF_Mobile-1-1-1.webp", 'alt' => 'Matchday Family Feast'],
        ['desktop' => $imgBase . "/2026/06/RSA_Matchday_10p-B_Desktop-1_50.webp", 'mobile' => $imgBase . "/2026/06/RSA_Matchday_10p-B_Mobile-1-1-1.webp", 'alt' => 'Matchday 10% Off Buckets'],
        ['desktop' => $imgBase . "/2026/06/RSA_Matchday_WF_Desktop-1_50.webp", 'mobile' => $imgBase . "/2026/06/RSA_Matchday_WF_Mobile-1-1-1.webp", 'alt' => 'Matchday Winglets'],
        ['desktop' => $imgBase . "/2026/06/RSA_Matchday_Mech_Desktop-1_50-1.webp", 'mobile' => $imgBase . "/2026/06/RSA_Matchday_Mech_Mobile-1-1-1-1-1.webp", 'alt' => 'Matchday Mechanics'],
        ['desktop' => $imgBase . "/2026/06/JOB-HL1015_RSA_SoccerMegaCombo_Websliders_R2_Web-1_50.webp", 'mobile' => $imgBase . "/2026/06/JOB-HL1015_RSA_SoccerMegaCombo_Websliders_R2_Mobi-1-1-1.webp", 'alt' => 'Soccer Mega Combo'],
    ],
    'menu-nav' => [
        ['id' => 'daily-deals', 'anchor' => 'anchordeals', 'title' => 'Daily Deals'],
        ['id' => 'chicken-meals', 'anchor' => 'anchorchickenmeals', 'title' => 'Chicken Meals'],
        ['id' => 'family-meals', 'anchor' => 'anchorfamilymeals', 'title' => 'Family Meals'],
        ['id' => 'buckets', 'anchor' => 'anchorbuckets', 'title' => 'Buckets'],
        ['id' => 'winglets', 'anchor' => 'anchorwinglets', 'title' => 'Winglets'],
        ['id' => 'burgers', 'anchor' => 'anchorburgers', 'title' => 'Burgers'],
        ['id' => 'chicken-fingers', 'anchor' => 'anchorchickenfingers', 'title' => 'Chicken Fingers'],
        ['id' => 'extras', 'anchor' => 'anchorextras', 'title' => 'Extras'],
        ['id' => 'sweet-treats', 'anchor' => 'anchorsweettreats', 'title' => 'Sweet Treats'],
        ['id' => 'drinks', 'anchor' => 'anchordrinks', 'title' => 'Drinks'],
    ],
    'menu-categories' => [
        ['id' => 'daily-deals', 'anchor' => 'anchordeals', 'title' => 'Daily Deals', 'image' => $imgBase . "/2025/08/DailyDeals.webp", 'radius' => 10, 'position' => 'center', 'image_only' => true],
        ['id' => 'chicken-meals', 'anchor' => 'anchorchickenmeals', 'title' => 'Chicken Meals', 'title_html' => 'Chicken<br>Meals', 'image' => $imgBase . "/2025/05/Thumbnail_Chicken-Meals-768x768.jpg.webp", 'radius' => 10, 'position' => 'center'],
        ['id' => 'family-meals', 'anchor' => 'anchorfamilymeals', 'title' => 'Family Meals', 'title_html' => 'Family<br>Meals', 'image' => $imgBase . "/2025/08/Family-Meals-ZIM.jpg", 'radius' => 15, 'position' => 'center'],
        ['id' => 'buckets', 'anchor' => 'anchorbuckets', 'title' => 'Buckets', 'title_html' => 'Buckets', 'image' => $imgBase . "/2025/08/bucket-category-3.webp", 'radius' => 15, 'position' => 'bottom center'],
        ['id' => 'winglets', 'anchor' => 'anchorwinglets', 'title' => 'Winglets', 'title_html' => 'Winglets', 'image' => $imgBase . "/2025/08/tdaphvvoi1x19ffnc7v5.webp", 'radius' => 15, 'position' => 'center', 'image_mobile' => $imgBase . "/2025/05/WINGLETS-MFO-768x768.png.webp"],
        ['id' => 'burgers', 'anchor' => 'anchorburgers', 'title' => 'Burgers', 'title_html' => 'Burgers', 'image' => $imgBase . "/2025/08/Burgers_ZIM.jpg", 'radius' => 10, 'position' => 'center'],
        ['id' => 'chicken-fingers', 'anchor' => 'anchorchickenfingers', 'title' => 'Chicken Fingers', 'title_html' => 'Chicken<br>Fingers', 'image' => $imgBase . "/2025/08/10ChickenFingers.webp", 'radius' => 15, 'position' => 'center'],
        ['id' => 'extras', 'anchor' => 'anchorextras', 'title' => 'Extras', 'title_html' => 'Extras', 'image' => $imgBase . "/2025/08/e88mlpbq3o3utcsnzw6s.webp", 'radius' => 15, 'position' => 'center'],
        ['id' => 'sweet-treats', 'anchor' => 'anchorsweettreats', 'title' => 'Sweet Treats', 'title_html' => 'Sweet<br>Treats', 'image' => $imgBase . "/2025/08/sweet-1.webp", 'radius' => 15, 'position' => 'center'],
        ['id' => 'drinks', 'anchor' => 'anchordrinks', 'title' => 'Drinks', 'title_html' => 'Drinks', 'image' => $imgBase . "/2025/08/DRINKS-768x768.png.webp", 'radius' => 15, 'position' => 'center'],
    ],
    'careers-banner' => ['image' => $imgBase . "/2026/06/1300x380-Final.jpg"],
    'sections' => [
        [
            'id' => 'chicken-meals',
            'anchor' => 'anchorchickenmeals',
            'title' => 'Chicken Meals',
            'items' => [
                ['name' => 'The Big One', 'price' => 'R32.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/The-Big-One.jpg-1024x1024.webp'],
                ['name' => 'Fomo For One', 'price' => 'R36.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-FOMO-FOR-ONE_1080x1080px.png-1024x1024.webp'],
                ['name' => 'Snack Pack', 'price' => 'R39.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-SNACK-PACK_1080x1080px.png-1024x1024.webp'],
                ['name' => 'Big Bite 2', 'price' => 'R39.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-BIG-BITE-2_1080x1080px.png-1024x1024.webp'],
                ['name' => 'Hungry Lion Mix Combo', 'price' => 'R56.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/HungryLionMix.png-1024x1024.webp'],
                ['name' => 'Big Bite 3', 'price' => 'R59.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-BIG-BITE-3_1080x1080px.png-1024x1024.webp'],
                ['name' => 'Big Bite Feast', 'price' => 'R66.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Big-Bite-Feast.png-1024x1024.webp'],
            ],
        ],
        [
            'id' => 'family-meals',
            'anchor' => 'anchorfamilymeals',
            'title' => 'Family Meals',
            'items' => [
                ['name' => '4 PIECE MEAL', 'price' => 'R75.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-4-PIECE-MEAL_1080x1080px-1024x1024.webp'],
                ['name' => 'KING COMBO', 'price' => 'R79.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-KING-COMBO_1080x1080px-1024x1024.webp'],
                ['name' => 'MEGA MEAL', 'price' => 'R119.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-MEGA-MEAL_1080x1080px-1024x1024.webp'],
                ['name' => 'PARTY MEAL', 'price' => 'R179.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Party-Meal_ZIM.jpg'],
                ['name' => 'Jumbo Meal', 'price' => 'R199.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-JUMBO-MEAL_1080x1080px-1024x1024.webp'],
            ],
        ],
        [
            'id' => 'buckets',
            'anchor' => 'anchorbuckets',
            'title' => 'Buckets',
            'items' => [
                ['name' => '6 Piece Bucket', 'price' => 'R109.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/7PieceBucket-1024x1024.webp'],
                ['name' => '10 Piece Bucket', 'price' => 'R159.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/9PcBucket-1024x1024.webp'],
                ['name' => '15 Piece Bucket', 'price' => 'R229.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/15PCBuckets-1024x1024.webp'],
                ['name' => '20 Piece Bucket', 'price' => 'R279.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/21PCBuckets-1024x1024.webp'],
            ],
        ],
        [
            'id' => 'winglets',
            'anchor' => 'anchorwinglets',
            'title' => 'Winglets',
            'items' => [
                ['name' => '6 Zamba Winglets', 'price' => 'R45.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/6-Zamba-Wings-1024x1024.webp'],
                ['name' => 'Zamba Wing Combo', 'price' => 'R69.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-ZAMBA-WING-COMBO_1080x1080px-1024x1024.webp'],
                ['name' => 'Zamba Wing Pack', 'price' => 'R89.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/10/Zamba-Wing-Pack-1-1024x1024.webp'],
                ['name' => '10 Zamba Spicy Winglets', 'price' => 'R69.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/10-ZAMBA-SPICY-WINGLETS-1024x1024.webp'],
                ['name' => '20 Zamba Spicy Winglets', 'price' => 'R129.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WingsBucket-01-1024x1024.webp'],
                ['name' => 'Sticky Wing IT', 'price' => 'R39.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/sticky-wing-it-1024x1024-1.jpg'],
                ['name' => '6 Sticky Wings', 'price' => 'R49.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/6-sticky-wings-1024x1024-1.png'],
                ['name' => 'Sticky Wing Combo', 'price' => 'R69.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/sticky-wing-combo-1024x1024-1.png'],
                ['name' => '10 Sticky Wings', 'price' => 'R79.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/10-sticky-wings-1024x1024-1.png'],
                ['name' => '20 Sticky Wings', 'price' => 'R149.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/20-sticky-wings-1024x1024-1.png'],
            ],
        ],
        [
            'id' => 'burgers',
            'anchor' => 'anchorburgers',
            'title' => 'Burgers',
            'items' => [
                ['name' => 'MUNCH BURGER', 'price' => 'R24.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/MUNCH-BURGER.png'],
                ['name' => 'Munch Meal', 'price' => 'R49.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Munch-Meal.png'],
                ['name' => 'DOUBLE MUNCH BURGER', 'price' => 'R39.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/DOUBLE-MUNCH.png'],
                ['name' => 'Double Munch Burger Meal', 'price' => 'R59.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/DBL-Munch-Meal.png'],
                ['name' => 'BIG BOSS', 'price' => 'R34.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/BIG-BOSS-1.png'],
                ['name' => 'Big Boss Meal', 'price' => 'R59.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Big-Boss-Meal.png'],
                ['name' => 'BIG BOSS CHEESE', 'price' => 'R39.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/BIG-BOSS-CHEESE.png'],
                ['name' => 'Big Boss Cheese Meal', 'price' => 'R64.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Burger-Mania-2.0_ProductImage_BigBossCheeseMeal.png'],
                ['name' => 'Double Big Boss burger', 'price' => 'R54.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/DBL-Big-Boss.png'],
                ['name' => 'DOUBLE BIG BOSS BURGER MEAL', 'price' => 'R79.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/DBL-Big-Boss-Meal.png'],
                ['name' => 'Triiiple Big Boss Burger', 'price' => 'R69.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Burger-Mania-2.0_ProductImage_TripleOnly.png'],
                ['name' => 'Triiiple Big Boss Meal', 'price' => 'R94.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/ProductImage_TripleMeal.png'],
            ],
        ],
        [
            'id' => 'chicken-fingers',
            'anchor' => 'anchorchickenfingers',
            'title' => 'Chicken Fingers',
            'items' => [
                ['name' => '3 Chicken Fingers & 1 Dippa', 'price' => 'R29.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/JOB-HL758_RSA_SweetMayoLaunch_UnityImage_3FingersDippa.jpg'],
                ['name' => '6 Chicken Fingers & 2 Dippa', 'price' => 'R49.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/6ChickenFingers-1024x1024.webp'],
                ['name' => 'Chicken Finger Meal', 'price' => 'R49.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/ChickenFingersMeal-1024x1024.webp'],
                ['name' => '10 Chicken Fingers & 3 Dippa', 'price' => 'R79.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/10ChickenFingers-1024x1024.webp'],
                ['name' => 'Chicken Finger Feast', 'price' => 'R99.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2026/02/JOB-HL909_RSA_FebFingers_WebImage.jpg'],
            ],
        ],
        [
            'id' => 'extras',
            'anchor' => 'anchorextras',
            'title' => 'Extras',
            'items' => [
                ['name' => 'Tangy Tomato Dippa', 'price' => 'R4.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/TangyTomato.png'],
                ['name' => 'Sweet Mayo Dippa', 'price' => 'R4.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/JOB-HL758_RSA_SweetMayoLaunch_UnityImage.jpg'],
                ['name' => 'Spicy Zamba Dippa', 'price' => 'R4.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/SpicyZamba.webp'],
                ['name' => 'Wing Hot Sauce', 'price' => 'R4.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WingHotSauce.webp'],
                ['name' => 'BBQ Dippa', 'price' => 'R4.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/BBQ.webp'],
                ['name' => 'Dixie Roll', 'price' => 'R9.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-DIXIE-ROLL_1080x1080px-1024x1024.webp'],
                ['name' => 'Coleslaw', 'price' => 'R13.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-COLESLAW_1080x1080px-1024x1024.webp'],
                ['name' => 'One Piece', 'price' => 'R22.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/One-Piece-1024x1024.webp'],
                ['name' => 'REGULAR CHIPS', 'price' => 'R23.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-REGULAR-CHIPS_1080x1080px-1024x1024.webp'],
                ['name' => 'Large Chips', 'price' => 'R26.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-LARGE-CHIPS_1080x1080px-1024x1024.webp'],
                ['name' => 'XL CHIPS', 'price' => 'R36.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/XLargeChips.jpg'],
                ['name' => 'CHIP BUCKET', 'price' => 'R89.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Chip-Bucket.jpg'],
            ],
        ],
        [
            'id' => 'sweet-treats',
            'anchor' => 'anchorsweettreats',
            'title' => 'Sweet Treats',
            'items' => [
                ['name' => 'VANILLA SUNDAE', 'price' => 'R9.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/VanillaSundae_Unity.jpg'],
                ['name' => 'Caramel Dipped Sundae', 'price' => 'R14.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Sundae_Caramel-1024x1024.webp'],
                ['name' => 'Chocolate Dipped Sundae', 'price' => 'R14.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/HL-Delivery_ChocDip-1024x1024.webp'],
                ['name' => 'King-Sized Vanilla Sundae', 'price' => 'R14.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/KingSizedVanilla.webp'],
                ['name' => 'Unicorn Sundae', 'price' => 'R19.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Unicorn.webp'],
                ['name' => 'Fruity Sundae', 'price' => 'R19.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/FruitySundae.webp'],
                ['name' => 'Mint Tart Sundae', 'price' => 'R26.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/MintTartSundae.webp'],
            ],
        ],
        [
            'id' => 'drinks',
            'anchor' => 'anchordrinks',
            'title' => 'Drinks',
            'items' => [
                ['name' => '300ml Pet', 'price' => 'R12.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/300ML-PET-1024x1024.webp'],
                ['name' => 'MINERAL WATER', 'price' => 'R12.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-MINERAL-WATER_1080x1080px-1024x1024.webp'],
                ['name' => 'SCORE', 'price' => 'R14.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/SCORE-1024x1024.webp'],
                ['name' => 'Cappy', 'price' => 'R16.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/CAPPY-1024x1024.webp'],
                ['name' => '440ML BOTTLE', 'price' => 'R16.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WEBSITE-440ML-BOTTLE_1080x1080px-1024x1024.webp'],
                ['name' => '1L Bottle', 'price' => 'R19.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/1586410890-1024x1024.jpg'],
                ['name' => 'Red Bull', 'price' => 'R19.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Red-Bull.webp'],
                ['name' => 'Monster 500ml', 'price' => 'R19.90', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/12/Monster.jpg'],
            ],
        ],
        [
            'id' => 'daily-deals',
            'anchor' => 'anchordeals',
            'title' => 'Daily Deals',
            'layout' => 'daily-deals',
            'tuesday' => [
                ['name' => '2 x Munch Burgers', 'price' => 'R35.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/2x-Munch-Burgers-Web-Image.jpg'],
                ['name' => '2 x Munch Meals', 'price' => 'R65.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Web_DoubleUp-Tuesday_2MunchMeals.jpg'],
                ['name' => 'Tuesday Two + 2 Drinks', 'price' => 'R89.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Web_DoubleUp-Tuesday_2BB2-1024x1024.png'],
            ],
            'wednesday' => [
                ['name' => 'Zamba Wing Combo', 'price' => 'R55.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Web_Wing-Wednesday_Zamba-Wing-Combo-1024x1024.webp'],
                ['name' => 'Zamba Wing Pack', 'price' => 'R75.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Web_Wing-Wednesday_Zamba-Wing-Pack-1024x1024.webp'],
                ['name' => '20 Wings', 'price' => 'R99.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/WingWednesday-1024x1024.webp'],
            ],
            'secondary' => [
                ['name' => 'Chip Bucket', 'price' => 'R75.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/Thursday-Buckets_Chip-Bucket_ZIM-1.jpg'],
                ['name' => 'Thursday 20 Wings', 'price' => 'R99.00', 'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/ThurBucket-01-1024x1024.webp'],
            ],
            'special' => [
                'name' => 'Thursday Buckets',
                'special' => true,
                'image' => 'https://www.hungrylion.co.za/wp-content/uploads/2025/08/ThurBucket-02-1024x1024.webp',
                'variants' => [
                    ['name' => '6 PIECE', 'price' => 'R95.00'],
                    ['name' => '10 PIECE', 'price' => 'R145.00'],
                    ['name' => '15 PIECE', 'price' => 'R215.00'],
                    ['name' => '20 PIECE', 'price' => 'R255.00'],
                ],
            ],
        ],
    ],
];
