<?php

declare(strict_types=1);

$imgBase = 'https://www.hungrylion.co.za/wp-content/uploads';

return [
    'hero-slides' => [
        ['desktop' => "{$imgBase}/2026/06/RSA_Football-Meal_FFF_Desktop.jpg", 'mobile' => "{$imgBase}/2026/06/RSA_Football-Meal_FFF_Mobile.jpg", 'alt' => 'Football Meal'],
        ['desktop' => "{$imgBase}/2026/06/RSA_Football-Meal_FDH_Desktop.jpg", 'mobile' => "{$imgBase}/2026/06/RSA_Football-Meal_FDH_Mobile.jpg", 'alt' => 'Football Meal'],
        ['desktop' => "{$imgBase}/2026/06/RSA_Matchday_FF_Desktop-1_50.webp", 'mobile' => "{$imgBase}/2026/06/RSA_Matchday_FF_Mobile-1-1-1.webp", 'alt' => 'Matchday Family Feast'],
        ['desktop' => "{$imgBase}/2026/06/RSA_Matchday_10p-B_Desktop-1_50.webp", 'mobile' => "{$imgBase}/2026/06/RSA_Matchday_10p-B_Mobile-1-1-1.webp", 'alt' => 'Matchday 10% Off Buckets'],
        ['desktop' => "{$imgBase}/2026/06/RSA_Matchday_WF_Desktop-1_50.webp", 'mobile' => "{$imgBase}/2026/06/RSA_Matchday_WF_Mobile-1-1-1.webp", 'alt' => 'Matchday Winglets'],
        ['desktop' => "{$imgBase}/2026/06/RSA_Matchday_Mech_Desktop-1_50-1.webp", 'mobile' => "{$imgBase}/2026/06/RSA_Matchday_Mech_Mobile-1-1-1-1-1.webp", 'alt' => 'Matchday Mechanics'],
        ['desktop' => "{$imgBase}/2026/06/JOB-HL1015_RSA_SoccerMegaCombo_Websliders_R2_Web-1_50.webp", 'mobile' => "{$imgBase}/2026/06/JOB-HL1015_RSA_SoccerMegaCombo_Websliders_R2_Mobi-1-1-1.webp", 'alt' => 'Soccer Mega Combo'],
    ],
    'menu-categories' => [
        ['id' => 'daily-deals', 'title' => 'Daily Deals', 'title_html' => 'Daily<br>Deals', 'image' => "{$imgBase}/2025/08/DailyDeals.webp", 'radius' => 10, 'position' => 'center'],
        ['id' => 'chicken-meals', 'title' => 'Chicken Meals', 'title_html' => 'Chicken<br>Meals', 'image' => "{$imgBase}/2025/05/Thumbnail_Chicken-Meals-768x768.jpg.webp", 'radius' => 10, 'position' => 'center'],
        ['id' => 'family-meals', 'title' => 'Family Meals', 'title_html' => 'Family<br>Meals', 'image' => "{$imgBase}/2025/08/Family-Meals-ZIM.jpg", 'radius' => 15, 'position' => 'center'],
        ['id' => 'buckets', 'title' => 'Buckets', 'title_html' => 'Buckets', 'image' => "{$imgBase}/2025/08/bucket-category-3.webp", 'radius' => 15, 'position' => 'bottom center'],
        ['id' => 'winglets', 'title' => 'Winglets', 'title_html' => 'Winglets', 'image' => "{$imgBase}/2025/08/tdaphvvoi1x19ffnc7v5.webp", 'image_mobile' => "{$imgBase}/2025/05/WINGLETS-MFO-768x768.png.webp", 'radius' => 15, 'position' => 'center'],
        ['id' => 'burgers', 'title' => 'Burgers', 'title_html' => 'Burgers', 'image' => "{$imgBase}/2025/08/Burgers_ZIM.jpg", 'radius' => 10, 'position' => 'center'],
        ['id' => 'chicken-fingers', 'title' => 'Chicken Fingers', 'title_html' => 'Chicken<br>Fingers', 'image' => "{$imgBase}/2025/08/10ChickenFingers.webp", 'radius' => 15, 'position' => 'center'],
        ['id' => 'extras', 'title' => 'Extras', 'title_html' => 'Extras', 'image' => "{$imgBase}/2025/08/e88mlpbq3o3utcsnzw6s.webp", 'radius' => 15, 'position' => 'center'],
        ['id' => 'sweet-treats', 'title' => 'Sweet Treats', 'title_html' => 'Sweet<br>Treats', 'image' => "{$imgBase}/2025/08/sweet-1.webp", 'radius' => 15, 'position' => 'center'],
        ['id' => 'drinks', 'title' => 'Drinks', 'title_html' => 'Drinks', 'image' => "{$imgBase}/2025/08/DRINKS-768x768.png.webp", 'radius' => 15, 'position' => 'center'],
    ],
    'careers-banner' => [
        'image' => "{$imgBase}/2026/06/1300x380-Final.jpg",
    ],
    'sections' => [
        [
            'id' => 'chicken-meals',
            'title' => 'Chicken Meals',
            'items' => [
                ['name' => 'The Big One', 'price' => 'R32.90'],
                ['name' => 'Fomo For One', 'price' => 'R36.90'],
                ['name' => 'Snack Pack', 'price' => 'R39.90'],
                ['name' => 'Big Bite 2', 'price' => 'R39.90'],
                ['name' => 'Hungry Lion Mix Combo', 'price' => 'R56.90'],
                ['name' => 'Big Bite 3', 'price' => 'R59.90'],
                ['name' => 'Big Bite Feast', 'price' => 'R66.90'],
            ],
        ],
        [
            'id' => 'family-meals',
            'title' => 'Family Meals',
            'items' => [
                ['name' => '4 Piece Meal', 'price' => 'R75.00'],
                ['name' => 'King Combo', 'price' => 'R79.00'],
                ['name' => 'Mega Meal', 'price' => 'R119.00'],
                ['name' => 'Party Meal', 'price' => 'R179.00'],
                ['name' => 'Jumbo Meal', 'price' => 'R199.00'],
            ],
        ],
        [
            'id' => 'buckets',
            'title' => 'Buckets',
            'items' => [
                ['name' => '6 Piece Bucket', 'price' => 'R109.00'],
                ['name' => '10 Piece Bucket', 'price' => 'R159.00'],
                ['name' => '15 Piece Bucket', 'price' => 'R229.00'],
                ['name' => '20 Piece Bucket', 'price' => 'R279.00'],
            ],
        ],
        [
            'id' => 'winglets',
            'title' => 'Winglets',
            'items' => [
                ['name' => '6 Zamba Winglets', 'price' => 'R45.00'],
                ['name' => 'Zamba Wing Combo', 'price' => 'R69.00'],
                ['name' => 'Zamba Wing Pack', 'price' => 'R89.00'],
                ['name' => '10 Zamba Spicy Winglets', 'price' => 'R69.00'],
                ['name' => '20 Zamba Spicy Winglets', 'price' => 'R129.00'],
                ['name' => 'Sticky Wing IT', 'price' => 'R39.00'],
                ['name' => '6 Sticky Wings', 'price' => 'R49.00'],
                ['name' => 'Sticky Wing Combo', 'price' => 'R69.00'],
                ['name' => '10 Sticky Wings', 'price' => 'R79.00'],
                ['name' => '20 Sticky Wings', 'price' => 'R149.00'],
            ],
        ],
        [
            'id' => 'burgers',
            'title' => 'Burgers',
            'items' => [
                ['name' => 'Munch Burger', 'price' => 'R24.90'],
                ['name' => 'Munch Meal', 'price' => 'R49.90'],
                ['name' => 'Double Munch Burger', 'price' => 'R39.90'],
                ['name' => 'Double Munch Burger Meal', 'price' => 'R59.90'],
                ['name' => 'Big Boss', 'price' => 'R34.90'],
                ['name' => 'Big Boss Meal', 'price' => 'R59.90'],
                ['name' => 'Big Boss Cheese', 'price' => 'R39.90'],
                ['name' => 'Big Boss Cheese Meal', 'price' => 'R64.90'],
                ['name' => 'Double Big Boss Burger', 'price' => 'R54.90'],
                ['name' => 'Double Big Boss Burger Meal', 'price' => 'R79.90'],
                ['name' => 'Triiiple Big Boss Burger', 'price' => 'R69.90'],
                ['name' => 'Triiiple Big Boss Meal', 'price' => 'R94.90'],
            ],
        ],
        [
            'id' => 'chicken-fingers',
            'title' => 'Chicken Fingers',
            'items' => [
                ['name' => '3 Chicken Fingers & 1 Dippa', 'price' => 'R29.90'],
                ['name' => '6 Chicken Fingers & 2 Dippa', 'price' => 'R49.90'],
                ['name' => 'Chicken Finger Meal', 'price' => 'R49.90'],
                ['name' => '10 Chicken Fingers & 3 Dippa', 'price' => 'R79.90'],
                ['name' => 'Chicken Finger Feast', 'price' => 'R99.00'],
            ],
        ],
        [
            'id' => 'extras',
            'title' => 'Extras',
            'items' => [
                ['name' => 'Tangy Tomato Dippa', 'price' => 'R4.90'],
                ['name' => 'Sweet Mayo Dippa', 'price' => 'R4.90'],
                ['name' => 'Spicy Zamba Dippa', 'price' => 'R4.90'],
                ['name' => 'Wing Hot Sauce', 'price' => 'R4.90'],
                ['name' => 'BBQ Dippa', 'price' => 'R4.90'],
                ['name' => 'Dixie Roll', 'price' => 'R9.90'],
                ['name' => 'Coleslaw', 'price' => 'R13.90'],
                ['name' => 'One Piece', 'price' => 'R22.90'],
                ['name' => 'Regular Chips', 'price' => 'R23.90'],
                ['name' => 'Large Chips', 'price' => 'R26.90'],
                ['name' => 'XL Chips', 'price' => 'R36.90'],
                ['name' => 'Chip Bucket', 'price' => 'R89.90'],
            ],
        ],
        [
            'id' => 'sweet-treats',
            'title' => 'Sweet Treats',
            'items' => [
                ['name' => 'Vanilla Sundae', 'price' => 'R9.90'],
                ['name' => 'Caramel Dipped Sundae', 'price' => 'R14.90'],
                ['name' => 'Chocolate Dipped Sundae', 'price' => 'R14.90'],
                ['name' => 'King-Sized Vanilla Sundae', 'price' => 'R14.90'],
                ['name' => 'Unicorn Sundae', 'price' => 'R19.90'],
                ['name' => 'Fruity Sundae', 'price' => 'R19.90'],
                ['name' => 'Mint Tart Sundae', 'price' => 'R26.90'],
            ],
        ],
        [
            'id' => 'drinks',
            'title' => 'Drinks',
            'items' => [
                ['name' => '300ml Pet', 'price' => 'R12.90'],
                ['name' => 'Mineral Water', 'price' => 'R12.90'],
                ['name' => 'Score', 'price' => 'R14.90'],
                ['name' => 'Cappy', 'price' => 'R16.90'],
                ['name' => '440ml Bottle', 'price' => 'R16.90'],
                ['name' => '1L Bottle', 'price' => 'R19.90'],
                ['name' => 'Red Bull', 'price' => 'R19.90'],
                ['name' => 'Monster 500ml', 'price' => 'R19.90'],
            ],
        ],
        [
            'id' => 'daily-deals',
            'title' => 'Daily Deals',
            'items' => [
                ['name' => '2 x Munch Burgers', 'price' => 'R35.00'],
                ['name' => '2 x Munch Meals', 'price' => 'R65.00'],
                ['name' => 'Tuesday Two + 2 Drinks', 'price' => 'R89.00'],
                ['name' => 'Zamba Wing Combo', 'price' => 'R55.00'],
                ['name' => 'Zamba Wing Pack', 'price' => 'R75.00'],
                ['name' => '20 Wings', 'price' => 'R99.00'],
                ['name' => 'Chip Bucket', 'price' => 'R75.00'],
                ['name' => 'Thursday 20 Wings', 'price' => 'R99.00'],
                ['name' => 'Thursday 6 Piece Bucket', 'price' => 'R95.00'],
                ['name' => 'Thursday 10 Piece Bucket', 'price' => 'R145.00'],
                ['name' => 'Thursday 15 Piece Bucket', 'price' => 'R215.00'],
                ['name' => 'Thursday 20 Piece Bucket', 'price' => 'R255.00'],
            ],
        ],
    ],
];
